---
- name: remove supervisor system package
  apt: pkg=supervisor state=absent

# pip install to obtain a consistent version number
- name: pip install supervisor
  pip: name=supervisor version=3.0

- name: install the jdk
  apt: name=openjdk-8-jre-headless state=present update-cache=yes cache_valid_time=3600

- name: set solr_filename
  set_fact:
    solr_filename: "solr-{{ solr_version }}"

- name: set solr_dir
  set_fact:
    solr_dir: "{{ root_dir }}/{{ solr_filename }}"

- name: check for existing solr installation
  stat: path={{ solr_dir }}
  register: solr_installed

- name: download solr
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: no
  when: solr_installed.stat.isdir is not defined

- name: extract solr
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ root_dir }}"
    copy: no
    remote_src: yes
    owner: "{{ project_name }}"
    group: "{{ project_name }}"
  when: solr_installed.stat.isdir is not defined

- name: copy the solr project directory
  command: cp -r example {{ project_name }}
  args:
    chdir: "{{ solr_dir }}"
    creates: "{{ solr_dir }}/{{ project_name }}"

- name: create copies for all of the cores
  command: cp -r {{ project_name }}/solr/collection1 {{ project_name }}/solr/{{ item }}
  args:
    chdir: "{{ solr_dir }}"
    creates: "{{ solr_dir }}/{{ project_name }}/solr/{{ item }}"
  with_items: "{{ solr_cores }}"

- name: remove collection1
  file: path={{ solr_dir }}/{{ project_name }}/solr/collection1 state=absent
  when: "'collection1' not in solr_cores"

# TODO
# - name: configure solr stopwords

# TODO
# - name: configure solr

- name: upload solr schema
  copy:
    src: "{{ solr_schema_file }}"
    dest: "{{ solr_dir }}/{{ project_name }}/solr/conf/"

- name: set the ownership and mode of the solr project directory
  file:
    path: "{{ solr_dir }}"
    state: directory
    owner: "{{ project_name }}"
    group: "{{ project_name }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: set up solr under supervisord
  template:
    src: solr.conf
    dest: /etc/supervisor/conf.d/{{ project_name }}-solr.conf
    owner: root
    group: root
    mode: 0644
  register: supervisor_solr

- name: reread supervisor conf files
  command: supervisorctl reread
  when: supervisor_solr|changed

- name: reload supervisord
  command: supervisorctl reload
  when: supervisor_solr|changed

- name: ensure solr is running
  supervisorctl: name={{ project_name }}-solr state=started
